---
title: "MATH 461. Applied Multivariate Statistics"
format: 
  html:
    toc: true
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

[Syllabus](syllabus.html)

| Date       | Section/Topic                                  | Notes                    | Assignments                         |
|----------------|------------------|----------------|-----------------------|
| **Week 1** |                                                |                          |                                     |
| 1/25       | Multiple Linear Regression                     | [Note](slides/mlr1.pdf)  | [Assignment 1](assignments/a1.html) |
| **Week 2** |                                                |                          |                                     |
| 1/30       | Multiple Linear Regression: Generalized F-test | [Note](slides/mlr2.pdf)  |                                     |
| 2/1        | Multiple Linear Regression: Generalized F-test | [Note](slides/mlr2.pdf)  | [Assignment 2](assignments/a2.html) |
| **Week 3** |                                                |                          |                                     |
| 2/6        | GLM - Logistic Regression                      | [Note](slides/3_glm.pdf) | [Assignment 3](assignments/a3.html) |
| 2/8        | GLM - Logistic Regression                      | [Note](slides/3_glm.pdf) | [Assignment 4](assignments/a4.html) |
| **Week 4** |                                                |                          |                                     |
| 2/13        | Working on Assignments                      | [Note](slides/3_glm.pdf) |  |
| 2/15        | GLM - Poisson Regression                      | [Note](slides/3_glm.pdf) | [Assignment 5](assignments/a5.html) |
| **Week 5** |                                                |                          |                                     |
| 2/20        | Working on Assignments                      | [Note](slides/3_glm.pdf) |  |
| 2/22        | GLM - SAS                      | [Note](slides/4_glm_gof.html) | [Assignment 6](assignments/a6.html) |
| **Week 6** |                                                |                          |                                     |
| 2/27        | K-means                      | [Note](slides/4.pdf) | [Assignment 7](assignments/a7.html) |
| 2/29        | K-means                      | [Note](slides/5.html) | [Assignment 8](assignments/a8.html) |
| **Week 7** |                                                |                          |                        |
| 3/5        | K-means                      |  |  |
| 3/7        | K-means                      | | |
| **Week 8** | Spring Break                                                |                          |                   |
| **Week 9** |                                                |                          |                        |
| 3/19        | Hierarchical Clustering           | [Slides](slides/6_h_clustering.html), [Note](slides/Hierarchical_Clustering.pdf)  | [Assignment 9](assignments/a9.html) |
| 3/21        | Hierarchical Clustering           | [Slides](slides/7_h_clustering_with_R.html), [Note](slides/Hierarchical_Clustering.pdf)  | [Assignment 10](assignments/a10.html) |
| **Week 10** |                                                |                          |                        |
| 3/26        | Clustering and Recommendation System           | [Slides](slides/8_clustering_rs.html)  | [Assignment 11](assignments/a11.html) |
| 3/268       | Clustering and Recommendation System           | [Slides](slides/8_clustering_rs.html)  | [Assignment 11](assignments/a11.html) |
| **Week 11** |                                                |                          |                        |
| 4/2        | PCA          | [Slides](slides/9_pca3.html)  | [Assignment 12](assignments/a12_codes.html) |
| **Week 12** |                                                |                          |                        |
| 4/9        | PCA          |  | [Assignment 13](assignments/a13_codes.html), [Assignment 14](assignments/a14.html) |
| 4/11        | Factor Analysis         | [Slides](slides/15_factor_analysis.html)  |  [Assignment 15](assignments/a15.html) |
| **Week 13** |                                                |                          |                        |
| 4/16        | LDA          | [Notes](slides/lda_note.pdf)  | [Assignment 16](assignments/a16.html) |
| 4/18        | LDA and QDA          | [Slides](slides/17_lda.html)  | [Assignment 17](assignments/a17.html) |
| **Week 14** |                                                |                          |                        |
| 4/23        | Final Project          |   | [Final Project](assignments/final.html) |
: {.striped .hover}
